id: P9CE47C63
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG4299
  instance_id: http://purl.bdrc.io/resource/IE1KG4299
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - མཁན་རིན་པོ་ཆེ་འཇམ་དཔལ་དོན་བརྒྱུད་ཉི་མའི་མཛད་རྣམ་རགས་བསྡུས་ཙམ་བཀོད་པ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P1KG4300
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    ec15101de6964d93a6d40b99bb63da3e:
      title: པོད ༡་མཁན་རིན་པོ་ཆེ་འཇམ་དཔལ་དོན་བརྒྱུད་ཉི་མའི་མཛད་རྣམ་རགས་བསྡུས་ཙམ་བཀོད་པ
      volume_number: 1
      base_file: UT1KG4299_I1PD100507_0000.txt
      reference: http://purl.bdrc.io/resource/VL0D713F64B2E98BAC
      image_group: I1PD100507
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG4299
  - http://purl.bdrc.io/resource/W1KG4299
  ocr_software: Namsel
created_at: '2021-12-22T10:40:44.713859'
last_modified_at: '2021-12-22T10:40:44.713865'
